apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-deploy
  labels: 
   app: mesh-app
   type: front-end
spec:
 replicas: 6
 selector:
  matchLabels: 
   app: mesh-app
   type: mesh-front-end
 template:
  metadata: 
   name: first-api-dec
   labels:
    app: mesh-app
    type: mesh-front-end
  spec:
   containers:
   - name: simple-api
     image: meshari93/mesh-web:v1
     ports:
        - containerPort: 80 